---
title: "About Me"
about:
  template: solana
  links:
    - icon: github
      text: Github
      href: https://github.com/mingdeyu
    - icon: linkedin
      text: Linkedin
      href: https://uk.linkedin.com/in/deyu-ming-03607230
    - icon: envelope
      text: Email
      href: deyu.ming.16@ucl.ac.uk
---

I am a Lecturer in Mathematics and Data Analytics in the School of Management (SoM) at University College London (UCL). My research focuses on methodological and computational developments of statistical and machine learning tools to quantify uncertainties of multi-physics and multi-disciplinary decision systems. My research interests lie in the integration and Uncertainty Quantification (UQ) of cross-disciplinary models, supporting fast decision-making to tackle the ever-growing challenges in physics, environmental science, and natural hazards.

Prior to joining SoM, I did my postgraduate degrees at the Imperial College London and ETH Zurich respectively. I then finished my PhD and worked as a postdoctoral researcher in the Department of Statistical Science at UCL.

---

## Job Opportunity

I am currently looking for a Research Fellow in Artificial Intelligence based at UCL SoM and Department of Mathematics. The post is funded by the EPSRC project ADD-TREES (AI-elevated Decision-support via Digital Twins for Restoring and Enhancing Ecosystem Services) and is available immediately until 31 March 2025. 

The post holder will work with economists, mathematicians, statisticians, and research software engineers (RSEs) to develop innovative AI techniques on bespoke and adaptive methods for automatic depp Gaussian process emulation of a network of multidisciplinary models, enabling real-time decision support for UK’s woodland expansion, a critical step in achieving UK’s commitment to Net Zero by 2050.

_Learn more about the project and how to apply [here](https://www.ucl.ac.uk/work-at-ucl/search-ucl-jobs/details?nPostingId=5844&nPostingTargetId=14510&id=Q1KFK026203F3VBQBLO8M8M07&LG=UK&languageSelect=UK&mask=ext). Applications close on 19 September 2023_.

