---
title: "Research & Teaching"
echo: false
---

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.1/css/all.css" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">

```{css}
.button {background-color: white;
  color: black;
  border: 1px solid black;}
  
.button:hover {
  background-color: black;
  color: white;
  border: 1px solid black;
}
```

```{r}
bt <- function(link, label, icon){
  bt_ccs <- downloadthis::download_link(
  link = link,
  button_label = label,
  button_type = "default",
  has_icon = TRUE,
  icon = icon,
  self_contained = FALSE,
  button_size = "small",
  class = "button"
  ) 
  shiny::HTML(gsub("\n", "", as.character(bt_ccs)))
}
```

## Publications
Septiandri, A., **Ming, D.**, DiazDelaO, A., Jendoubi, T., and Ray S. (2025) Integrative analysis and imputation of multiple data streams via deep Gaussian processes. _Bioinformatics Advances_, _in press_.

`r bt("http://arxiv.org/abs/2505.12076", "Preprint", "far fa-file-pdf")`

Yang, Y., **Ming, D.**, and Guillas, S. (2025) Distribution of deep Gaussian process gradients and sequential design for simulators with sharp variations. arXiv:2503.16027. _Under Review_.

`r bt("http://arxiv.org/abs/2503.16027", "Preprint", "far fa-file-pdf")`

Zhuang, C., **Ming, D.**, Yuan, M., Makasis, N., Kreitmair J., M., & Choudhary, R. (2024). Linked Deep Gaussian Process for Digital Twins in Building Energy Systems. In _Proceedings of ASim Conference 2024: 5th Asia Conference of IBPSA_. Osaka, Japan. 

`r bt("http://doi.org/10.69357/asim2024.1277", "DOI", "ai ai-open-access ai-lg")`

**Ming, D.** and Williamson, D. (2023) Linked deep Gaussian process emulation for model networks. arXiv:2306.01212.

`r bt("http://arxiv.org/abs/2306.01212", "Preprint", "far fa-file-pdf")`

**Ming, D.**, Williamson, D., and Guillas, S. (2023) Deep Gaussian process emulation using stochastic imputation. _Technometrics_. 65(2), 150-161.

`r bt("https://arxiv.org/abs/2107.01590", "Preprint", "far fa-file-pdf")` `r bt("https://doi.org/10.1080/00401706.2022.2124311", "DOI", "ai ai-open-access ai-lg")`  

**Ming, D.** and Guillas, S. (2021) Linked Gaussian process emulation for systems of computer models using Matérn kernels and adaptive design. _SIAM/ASA Journal on Uncertainty Quantification_. 9(4), 1615-1642.

`r bt("https://doi.org/10.48550/arXiv.1912.09468", "Preprint", "far fa-file-pdf")` `r bt("https://doi.org/10.1137/20M1323771", "DOI", "ai ai-open-access ai-lg")`

## Research Grants

**Knowledge Transfer Partnership** (£220,000), _Innovate UK & Howden Re_, PI (Academic Supervisor), 2025-2027

**Development and Calibration of a Mixed-Species Model for Enhanced Woodland Creation Support** (£160,000), _BBSRC_, Co-I on Model Calibration, 2024-2025

**ADD-TREES: AI-elevated Decision-support via Digital Twins for Restoring and Enhancing Ecosystem Services** (£2M), _EPSRC_, Co-I on AI development, 2023-2025

`r bt("https://netzeroplus.ac.uk/project/add-trees/", "Website", "fa fa-globe")` `r bt("https://youtu.be/0PosmroCy4A?si=tvwEKqBfZ_uvdsuy", "Video", "fa fa-video")`
 
**NetZeroPlus: Sustainable Treescapes Demonstrator and Decision Tools** (£4M), _BBSRC_, Co-I on emulator development, 2022-2023

`r bt("https://netzeroplus.ac.uk/project/net-zero-plus/", "Website", "fa fa-globe")`

## Non-Peer-Reviewed Manuscripts

**Ming, D.** (2020) Notes on Seismic Source Models in Elastostatic. EarthArXiv.

`r bt("https://doi.org/10.31223/osf.io/234kp", "Preprint", "far fa-file-pdf")`

## Teaching

**University College London**

- International Business Analytics (BSc International Management)
- Data Analytics II (BSc Management Science)
- Mathematics III (Probability Theory)

**ESCP Business School**

- Statistics I: Statistics and Probability



