---
title: "Talks"
echo: false
---

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.1/css/all.css" crossorigin="anonymous"> <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/jpswalsh/academicons@1/css/academicons.min.css">

```{css}
.button {background-color: white;
  color: black;
  border: 1px solid black;}
  
.button:hover {
  background-color: black;
  color: white;
  border: 1px solid black;
}
```

```{r}
bt <- function(link, label, icon){
  bt_ccs <- downloadthis::download_link(
  link = link,
  button_label = label,
  button_type = "default",
  has_icon = TRUE,
  icon = icon,
  self_contained = FALSE,
  button_size = "small",
  class = "button"
  ) 
  shiny::HTML(gsub("\n", "", as.character(bt_ccs)))
}
```

## 2024
- Dec 2024, **Conference on Computational and Methodological Statistics** (invited)
- Jul 2024, **BNP Networking Workshop** (Contributing)
- Feb 2024, **SIAM Conference on Uncertainty Quantification (UQ24)** (invited)
- Feb 2024, **UCL Physical Geography Seminar** (invited)

## 2022 - 2023

- Oct 2023, **65th Annual Fall Technical Conference** (invited)
- Sep 2023, **RSS International Conference** (invited)
- Apr 2022, **SIAM Conference on Uncertainty Quantification** (invited)
- Feb 2022, **UCL-MOAP Workshop on Bayesian Machine Learning for Weather and Climate** (invited)

## 2016 - 2021

- Sep 2021, **UQ Reading Group**, University of Exeter (invited)
- Sep 2020, **GdR Mascot-Num meeting** (contributing)
- Jul 2020, **Centre for Doctoral Training in Foundational AI**, UCL (invited)
- Mar 2020, **SIAM Conference on Uncertainty Quantification** (invited)
- Jan 2020, **Data-Centric Engineering Group**, Alan Turing Institute (invited)
- Aug 2019, **Effective and Efficient Gaussian Processes**, Alan Turing Institute (invited)
- Jun 2018, **16th European Conference on Earthquake Engineering** (contributing)
- May 2018, **4th International Conference on Continental Earthquakes** (contributing)
- Nov 2017, **NatCat and Earthquake Modelling Workshop**, RiskLab, ETH Zurich (invited)
- Dec 2016, **Workshop on Earthquake Modelling**, RiskLab, ETH Zurich (invited)

